//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace BarCodeClient.WSBarcodeGenerator {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BarCodeGeneratorSoap", Namespace="http://tempuri.org/")]
    public class BarCodeGenerator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BarCodeGenerator() {
            this.Url = "http://localhost/wsBarCode/barcode.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Code39", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] Code39(string code, int barSize, bool showCodeString, string title) {
            object[] results = this.Invoke("Code39", new object[] {
                        code,
                        barSize,
                        showCodeString,
                        title});
            return ((System.Byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCode39(string code, int barSize, bool showCodeString, string title, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Code39", new object[] {
                        code,
                        barSize,
                        showCodeString,
                        title}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Byte[] EndCode39(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Byte[])(results[0]));
        }
    }
}
